### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [jakearchibald/ebook-demo#2]
Hi yeah! This repo is fab. 😸 @dauwhe pointed me here as I'm helping (a bit) with his [acme-labs](https://github.com/dauwhe/acme-labs/) project.

I'm guessing from your other repos that you intend to MIT this one also, but I like to check as without a `LICENSE` file or other declaration...it's technically All Rights Reserved (at least most places on the 🌐).

Mind adding a license note some place or other? We'd appreciate it! :grin:

Thanks!
🎩

**Comment by jakearchibald** [comment]
Added in https://github.com/jakearchibald/ebook-demo/commit/e28865919fb7c93b07753828a2ffb3dbf7e632c9

Sorry I lost track of this!
